apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongo-deployment
  labels:
    db: mongo

spec:
  template:
    metadata:
      name: mongo-pod
      labels:
        db: mongo
    spec: 
      containers:
        - name: mongo-container
          image: mongo
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom: 
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_INITDB_DATABASE
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc
  replicas: 1
  selector:
    matchLabels: 
      db: mongo